{
 "title": "Storj-Log-Exporter-Boom-Table",
 "tags": [
  "storj",
  "docker",
  "prometheus",
  "exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node:",
    "query": {
     "query": "label_values(storj_nodeID_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Combined summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs watched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(storj_log_levels{instance=~\"$node.*\",loglevel=\"INFO\"})",
     "legendFormat": "Nodes watched"
    }
   ]
  },
  {
   "title": "Log Entries (within time range)",
   "type": "stat",
   "description": "Number of changes in log entries of the different log levels. (Errors will disappear e.g. shown as 0 if there are no new messages within the chosen timeframe)\nError Count excludes falsely classified errors (e.g. shutdown of runner, download/upload failed due to client side errors, graceful exit errors if you GE'ed on stefan-benten).",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(storj_log_levels{instance=~\"$node.*\",loglevel=\"INFO\"})",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(storj_log_levels{instance=~\"$node.*\",loglevel=\"WARN\"}) OR vector(0)",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(storj_log_errors{instance=~\"$node.*\",type!=\"gracefulexit:service\\tfailed to get satellite address\",type!=\"piecestore\\tdownload failed\",type!=\"piecestore\\tupload failed\",type!=\"servers\\tunexpected shutdown of a runner\"}) OR vector(0)",
     "legendFormat": "Error (cor.)"
    },
    {
     "expr": "sum(storj_log_levels{instance=~\"$node.*\",loglevel=\"FATAL\"})  OR vector(0)",
     "legendFormat": "Fatal"
    }
   ]
  },
  {
   "title": "Successrates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_pieces_upload_successful{instance=~\"$node.*\"})/sum(storj_pieces_upload_started{instance=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(storj_pieces_upload_canceled{instance=~\"$node.*\"})/sum(storj_pieces_upload_started{instance=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload canceled"
    },
    {
     "expr": "sum(storj_pieces_upload_rejected{instance=~\"$node.*\"})/sum(storj_pieces_upload_started{instance=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload rejected"
    },
    {
     "expr": "sum(storj_pieces_download_successful{instance=~\"$node.*\"})/sum(storj_pieces_download_started{instance=~\"$node.*\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(storj_pieces_download_canceled{instance=~\"$node.*\"})/sum(storj_pieces_download_started{instance=~\"$node.*\"})",
     "legendFormat": "Download canceled"
    },
    {
     "expr": "sum(storj_pieces_delete_successful{instance=~\"$node.*\"})/(sum(storj_pieces_delete_successful{instance=~\"$node.*\"})+sum(storj_pieces_delete_failed{instance=~\"$node.*\"} OR vector(0)))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(storj_pieces_download_successful{instance=~\"$node.*\",type=\"audit\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(storj_pieces_download_failed{instance=~\"$node.*\",type=\"audit\",error=~\"file not found\"}) OR vector(0)",
     "legendFormat": "Recoverable"
    },
    {
     "expr": "sum(storj_pieces_download_failed{instance=~\"$node.*\",type=\"audit\",error=\"file not found\"}) OR vector(0)",
     "legendFormat": "Unrecoverable"
    }
   ]
  },
  {
   "title": "Net IO average (pieces per second)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_pieces_upload_successful{instance=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Net in"
    },
    {
     "expr": "sum(rate(storj_pieces_download_successful{instance=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Net out"
    },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{instance=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Net delete"
    }
   ]
  },
  {
   "title": "Average Piece Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{instance=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{instance=~\"$node.*\"}[5m]))",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{instance=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{instance=~\"$node.*\"}[5m]))",
     "legendFormat": "Egress"
    }
   ]
  },
  { "title": "Net IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Net IO by node (stacked)",
   "type": "graph",
   "description": "Pieces per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_pieces_download_successful{instance=~\"$node.*\"}[$__rate_interval])) by(instance)",
     "legendFormat": "RateOut {{instance}}"
    },
    {
     "expr": "sum(rate(storj_pieces_upload_successful{instance=~\"$node.*\"}[$__rate_interval])) by(instance)",
     "legendFormat": "RateIn {{instance}}"
    },
    { "expr": "0", "legendFormat": "0" },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{instance=~\"$node.*\"}[$__rate_interval])) by(instance)",
     "legendFormat": "RateDelete {{instance}}"
    }
   ]
  },
  {
   "title": "Net IO by satellite (stacked)",
   "type": "graph",
   "description": "Pieces per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_pieces_download_successful{instance=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "RateOut {{url}}"
    },
    {
     "expr": "sum(rate(storj_pieces_upload_successful{instance=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "RateIn {{url}}"
    },
    { "expr": "0", "legendFormat": "0" },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{instance=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "RateDelete {{url}}"
    }
   ]
  },
  { "title": "Successrates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Successrate Upload by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(storj_pieces_upload_successful{instance=~\"$node.*\"}) by(instance)/sum(storj_pieces_upload_started{instance=~\"$node.*\"}) by(instance)",
     "legendFormat": "Upload {{instance}}"
    },
    {
     "expr": "sum(storj_pieces_upload_successful{instance=~\"$node.*\"})/sum(storj_pieces_upload_started{instance=~\"$node.*\"})",
     "legendFormat": "Upload average"
    }
   ]
  },
  {
   "title": "Successrate Download by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(storj_pieces_download_successful{instance=~\"$node.*\"}) by(instance)/sum(storj_pieces_download_started{instance=~\"$node.*\"}) by(instance)",
     "legendFormat": "Download {{instance}}"
    },
    {
     "expr": "sum(storj_pieces_download_successful{instance=~\"$node.*\"})/sum(storj_pieces_download_started{instance=~\"$node.*\"})",
     "legendFormat": "Download average"
    }
   ]
  },
  { "title": "Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Piece Size (per satellite)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "Sum-out (-) / Sum-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{instance=~\"$node.*\"}[$__rate_interval])) by(url) / sum(rate(storj_pieces_upload_successful{instance=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "IngressPieceSize-{{url}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{instance=~\"$node.*\"}[$__rate_interval])) by(url) / sum(rate(storj_pieces_download_successful{instance=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "EgressPieceSize-{{url}}"
    }
   ]
  },
  {
   "title": "Errors Debug",
   "type": "stat",
   "description": "Missing Error messages in storj_log_errors filter. If this is >0, please send me your error logs.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(storj_log_levels{instance=~\"$node.*\",loglevel=\"ERROR\"})-sum(storj_log_errors{instance=~\"$node.*\",loglevel=\"ERROR\"})",
     "legendFormat": "Errors per minute"
    }
   ]
  },
  {
   "title": "Errors by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(storj_log_errors{instance=~\"$node.*\",type!=\"gracefulexit:service\\tfailed to get satellite address\",type!=\"piecestore\\tdownload failed\",type!=\"piecestore\\tupload failed\",type!=\"servers\\tunexpected shutdown of a runner\"}) by(instance,type) OR vector(0)",
     "legendFormat": "Errors {{instance}}: {{type}}"
    },
    {
     "expr": "sum(storj_log_levels{instance=~\"$node.*\",loglevel=\"FATAL\"}) by(instance,type) OR vector(0)",
     "legendFormat": "Fatal {{instance}}: {{type}}"
    }
   ]
  }
 ]
}